-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Autocmds are automatically loaded on the VeryLazy event
-- Add any additional autocmds here

-- local format_is_enabled = false
--
-- local function augroup(name)
--   return vim.api.nvim_create_augroup("zinsani_" .. name, { clear = true })
-- end
--
-- local _augroups = {}
-- local get_augroup = function(client)
--   if not _augroups[client.id] then
--     local group_name = "kickstart-lsp-format-" .. client.name
--     local id = vim.api.nvim_create_augroup(group_name, { clear = true })
--     _augroups[client.id] = id
--   end
--
--   return _augroups[client.id]
-- end
--
-- -- Whenever an LSP attaches to a buffer, we will run this function.
-- --
-- -- See `:help LspAttach` for more information about this autocmd event.
-- vim.api.nvim_create_autocmd("LspAttach", {
--   group = augroup("lsp-attach-format"),
--   -- This is where we attach the autoformatting for reasonable clients
--   callback = function(args)
--     local client_id = args.data.client_id
--     local client = vim.lsp.get_client_by_id(client_id)
--     local bufnr = args.buf
--
--     -- Only attach to clients that support document formatting
--     if not client.server_capabilities.documentFormattingProvider then
--       return
--     end
--
--     -- Tsserver usually works poorly. Sorry you work with bad languages
--     -- You can remove this line if you know what you're doing :)
--     -- if client.name == "tsserver" or client.name == "volar" then
--     --   return
--     -- end
--
--     -- Create an autocmd that will run *before* we save the buffer.
--     --  Run the formatting command for the LSP that has just attached.
--     vim.api.nvim_create_autocmd("BufWritePre", {
--       group = get_augroup(client),
--       buffer = bufnr,
--       callback = function()
--         if not format_is_enabled then
--           return
--         end
--
--         vim.lsp.buf.format({
--           async = false,
--           filter = function(c)
--             return c.id == client.id
--           end,
--         })
--       end,
--     })
--   end,
-- })
